export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const SET_LOGOUT = "SET_LOGOUT";
export const SET_LOGIN_RESPONSE = "SET_LOGIN_RESPONSE";
export const SET_ONBOARDING = "SET_ONBOARDING";
export const SET_TOOLTIP = "SET_TOOLTIP";

export const UPDATE_MESSAGES = "UPDATE_MESSAGES";
export const UPDATE_LOBBY_DATA = "UPDATE_LOBBY_DATA";
export const SET_PAGE = "SET_PAGE";

export const SET_GAME_REQUESTING = "SET_GAME_REQUESTING";
export const SET_GAME_REQUESTED = "SET_GAME_REQUESTED";
export const SET_START_GAME = "SET_START_GAME";

export const SET_MOVEMENT = "SET_MOVEMENT";
export const SET_GAME_OVER = "SET_GAME_OVER";