export const LOGIN_STATUS = {
  LOGGED_OUT: "LOGGED_OUT",
  REQUESTED: "REQUESTED",
  SUCCESSFUL: "SUCCESSFUL",
  FAILED: "FAILED",
  INVALID: "INVALID",
  REPEATED: "REPEATED"
}

export const REGISTER_STATUS = {
  CLOSE: "CLOSE",
  OPEN: "OPEN",
  REQUESTED: "REQUESTED",
  SUCCESSFUL: "SUCCESSFUL",
  FAILED: "FAILED",
  REPEATED: "REPEATED"
}

export const MODAL_TYPE = {
  REQUESTED: "REQUESTED",
  REQUESTING: "REQUESTING",
  GAMEOVER: "GAMEOVER",
  NONE: "NONE"
}

export const PAGE = {
  LOGIN: "LOGIN",
  GAME: "GAME",
  LOBBY: "LOBBY"
}

export const TOOLTIP = {
  NONE: "NONE",
  SEND_MESSAGE: "SEND_MESSAGE",
  REQUEST_GAME: "REQUEST_GAME",
  MENU: "MENU"
}