export const LOGIN_STATUS = {
  LOGGED_OUT: "LOGGED_OUT",
  REQUESTED: "REQUESTED",
  SUCCESSFUL: "SUCCESSFUL",
  FAILED: "FAILED",
  INVALID: "INVALID",
  REPEATED: "REPEATED"
}

export const MODAL_TYPE = {
  REQUESTED: "REQUESTED",
  REQUESTING: "REQUESTING",
  GAMEOVER: "GAMEOVER",
  NONE: "NONE"
}

export const PAGE = {
  LOGIN: "LOGIN",
  GAME: "GAME",
  LOBBY: "LOBBY"
}

export const TOOLTIP = {
  NONE: 0,
  SEND_MESSAGE: 1,
  REQUEST_GAME: 2,
  MENU: 3
}